### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by DataHippo93** [Magisk-Modules-Grave/chinese_sim_supporter#2]
I have a rooted pixel 3XL with Magisk installed and android 10. 

How can I use this code as a magisk module? I searched high and low for a way to use pixel 3XL with china telecom and this is my last attempt.

**Comment by apporc** [comment]
If you've successfully installed MagiskManager with Magisk on your phone, you should be able to see this module in MagiskManager -> Downloads, then you can just click it and install.

If there are problems of your Magisk installation, check [this](https://topjohnwu.github.io/Magisk/install.html).

**Comment by DataHippo93** [comment]
What should I search for? It doesn't appear to be available in the list of downloads

**Comment by DataHippo93** [comment]
Ok. I got it to work. Need to download zip and then create a new .zip with just the files and not the folder chinese-sim-supporter-master.

This is great! Thank you so much for making this. Let me know if you ever need anything. 

Maybe add to the readme.

**Comment by apporc** [comment]
Have you tried to search in "Downloads", with the name, or just "Chinese".
I can see this module in that list, I don't know why you have trouble
searching it.

If this works for everyone, then there is no need to update the manual. And
it should work.
